var DataBase = [
  ["Liha-Makaronilaatikko","Kuka nyt ei pitäisi perinteisestä Suomalaisesta makaronilaatikosta!"],
  ["Miilunpolttajan pasta","Desc"],
  ["Lasagne","Desc3"],
  ["Kinkkukiusaus","Desc3"],
  ["Itsetehty pizza","Desc3"],
  ["Kermainen Jauhelihakastike","Desc3"],
  ["Makkarakastike","Desc3"],
  ["Ruskea Jauhelihakastike","Desc3"],
  ["Jauhelihakeitto","Desc3"],
  ["Kanakeitto","Desc3"],
  ["Makkarakeitto","Desc3"],
  ["Kanakastike","Desc3"],
  ["Pyttipannu","Desc3"],
  ["Kananuudeli wokki","Desc3"],
  ["Uunilohi","Desc3"],
  ["Lihapullat","Desc3"],
  ["Tortillat","Desc3"],
  ["Spagetti bolognese","Desc3"],
  ["Kanan koipireidet","Desc3"],
  ["Lohipasta","Desc3"],
  ["Lihamureke","Desc3"],
  ["Natcho pelti","Desc3"],
  ["Tomaatti jauheliha paistos","Tunnetaan myös 'nistipatana'"],
  ["Nakit ja ranut","Desc3"],
  ["Kalapuikot ja ranut","Desc3"],
]
